### ISSUE TITLE
Visual features activation visualization in networks

### ISSUE THREAD

**Issue by alfrem** [maikherbig/AIDeveloper#11]
Woud be nice to be able to see visually what features are being extracted in layers for cnn.

It's possible, too, to see heatmaps over images with those features. Saliencys and Grad-cams.

As seen in: 
https://raghakot.github.io/keras-vis/vis.visualization/

https://towardsdatascience.com/visualizing-intermediate-activation-in-convolutional-neural-networks-with-keras-260b36d60d0

https://machinelearningmastery.com/how-to-visualize-filters-and-feature-maps-in-convolutional-neural-networks/

https://analyticsindiamag.com/openai-launches-microscope-to-better-understand-neural-networks-in-popular-machine-learning-models/

Its very spectacular when implemented, specially for teaching reasons.

**Comment by alfrem** [comment]
Great! :D

**Comment by maikherbig** [comment]
I found a method called Grad-CAM
You can now show the activation from an arbitrary layer. To do so, go to the "Assess Model" tab. Load a model and some data. Hit "Update plots" and then double click some item of the confusion matrix. The presented popup window now has options to show heatmaps or to create an overlay of the image and the heatmap. 
Commits:
76e031e
21ee953
9332f6e
