### ISSUE TITLE
Option for plotting models

### ISSUE THREAD

**Issue by alfrem** [maikherbig/AIDeveloper#12]
It can be good, for teaching and validation reasons, that models can be loaded as an image with plot_model.

plot_model with from keras.utils.vis_utils import plot_model

Thank you.

**Comment by maikherbig** [comment]
Please use an external software for that. For example netron:
https://github.com/lutzroeder/netron
Install it and then just load the .model files created by AIDeveloper.
![Answer_](https://user-images.githubusercontent.com/14074051/79495749-5ff10e00-8025-11ea-8e1f-ca545459cea3.png)
