### ISSUE TITLE
Error when moving vertical slider in ImageView (Confusion Matrix)

### ISSUE THREAD

**Issue by maikherbig** [maikherbig/AIDeveloper#14]
Thanks to @alfrem for reporting this error:
When predicting RGB images and selecting "Show" after double-clicking and item on the Confusion Matrix, the images are shown (all fine). But when moving the rightmost arrow (vertical, indicated in image below) there is an error thrown.
-> this issue goes back to pyqtgraph and is solved in version 0.11.0
-> solve issue by updating pyqtgraph (conda install -c anaconda pyqtgraph)
![error_report](https://user-images.githubusercontent.com/14074051/79635649-63de7680-8172-11ea-976d-355e6da09de9.png)

**Comment by maikherbig** [comment]
solved via 9f05886

**Comment by alfrem** [comment]
Great work!El 21 abr. 2020 0:22, Maik Herbig <notifications@github.com> escribió:
Closed #14.
