### ISSUE TITLE
Unable to change layer number in transfer learning

### ISSUE THREAD

**Issue by Sophyzhq** [maikherbig/AIDeveloper#51]
In addition to accuracy, other metrics, such as precision and recall, are chosen when I conduct transfer learning. The layer number in the blank of Train only last N layers in Expert Mode is unable to be changed in the process of training. If I try to change the layer number, the training will immediately stop.
In contrast, the layer number could be changed when only accuracy is chosen.
Here is the screenshot of the error message.
![problem](https://user-images.githubusercontent.com/92014991/158524556-5f19f444-792a-4b6b-87a7-f297d772c8e9.png)

**Comment by maikherbig** [comment]
Thanks @Sophyzhq for reporting!
Issue is solved via [10fde22](https://github.com/maikherbig/AIDeveloper/commit/10fde2290a0def697e80eff6eff5a78f4c9ddcdb)
