### ISSUE TITLE
support more than 99 class

### ISSUE THREAD

**Issue by aaaboypop** [maikherbig/AIDeveloper#52]
I have a project that requires more than 99 classes, but the program now has a limit of 99.
Is it possible to have a limit for more than that? (3 digit number)
![image](https://user-images.githubusercontent.com/13348147/199592196-e2655134-9384-4168-b1a7-25788f3c7f96.png)

**Comment by maikherbig** [comment]
Thanks for pointing out that  bug! I solved the issue in this new update:
https://github.com/maikherbig/AIDeveloper/releases/tag/0.4.5-update

One more thing and sorry for bothering in case you already figured out:
Working with that many files can be time consuming in AIDeveloper. In such cases (many files/many classes) I like to do the following:
1.  import all data into AIDeveloper. May take a while
2. Click 'File' -> 'Save session' which saves the table to an exel file
3. Use Excel to manipulate class labels, number of images per epoch etc. Save the changes.
4. In AIDeveloper, click 'File' -> 'Load session'
