### ISSUE TITLE
Error when load session with more than 99 class

### ISSUE THREAD

**Issue by aaaboypop** [maikherbig/AIDeveloper#53]
Whenever there are more than 99 classes loaded, an error message will repeatedly appear.

![AIDeveloper_0 4 0_vR17W4it57](https://user-images.githubusercontent.com/13348147/199609056-eec540b2-515a-46f0-be61-bcd5f58ab12b.png)

**Comment by maikherbig** [comment]
Thanks so much for your detailed desription of the issue and the screenshot! This helped a lot.
Hopefully this bug is solved now:
https://github.com/maikherbig/AIDeveloper/releases/tag/0.4.6-update

**Comment by aaaboypop** [comment]
First and foremost, thank you for the quick update.
This resolved my issue :)
