### ISSUE TITLE
No way to import unclassified data

### ISSUE THREAD

**Issue by jonathancolledge** [maikherbig/AIDeveloper#58]
Hi,
Another request for help please - I can find no way to assess the model with unclassified data. If I import data, it always gets assigned a class and I can't choose no class. What am I missing?
Thanks,
Jonathan

**Comment by maikherbig** [comment]
I think you are looking for the "Classify unlabeled data" region which you can find in the tab "Assess model". This function is explained in following tutorial:
https://youtu.be/dvFiSRnwoto?t=673

**Comment by jonathancolledge** [comment]
Thank you for this. Sorry about the lack of reply. I think the issue was the corrupted model I was trying to use. (As an aside, I figured out why it went to so many epochs so quickly - I had steps/epoch incorrectly set to 100).
