### ISSUE TITLE
Implementing last "very deep" models

### ISSUE THREAD

**Issue by alfrem** [maikherbig/AIDeveloper#9]
Just as an idea. Would be interesting to have AlexNet, ResNet or SqueezeNet. 

Resnet can be tricky with parallelism and residual module but provide excelent results.

Thank you.

**Comment by alfrem** [comment]
I suppose this can be done in model_zoo.py, right?

**Comment by maikherbig** [comment]
yes :)
just follow the example of the vgg19 or so. Let me know if it worked!

**Comment by maikherbig** [comment]
ResNet is now implemented: c3fc8b6
(for this to work you need keras applications >=1.0.7; this is installed by default when you install keras v >=2.2.4)
The rest of AIDeveloper will now be adjusted to work with keras v. 2.2.4

**Comment by maikherbig** [comment]
SqueezeNet could be taken from here:
https://github.com/rcmalli/keras-squeezenet

**Comment by maikherbig** [comment]
SqueezeNet is now added to the model_zoo:  3662af5

**Comment by maikherbig** [comment]
ResNet v2 is not working:
Error:
module 'keras.applications' has no attribute 'resnet'

**Comment by maikherbig** [comment]
Solved via  80696fc
